apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-module-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-module
  template:
    metadata:
      labels:
        app: auth-module
    spec:
      containers:
      - name: auth-module
        image: yourusername/auth-module:1.0.0  # Replace with your actual image
        ports:
        - containerPort: 3000
