apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-module-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-module
  template:
    metadata:
      labels:
        app: auth-module
    spec:
      containers:
      - name: auth-module
        image: auth-module  # You will set the actual image dynamically via your CI/CD pipeline
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
