apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-module-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-module
  template:
    metadata:
      labels:
        app: auth-module
    spec:
      containers:
      - name: auth-module
        # Ensure to use the correct tag as used in your Docker image building process.
        # For example, if your image tag is "v1.0", specify "auth-module:v1.0".
        # Using "latest" tag or a specific version tag is recommended for clarity.
        image: auth-module:v1.0
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent


